eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/userservice/**
          filters:
            - RewritePath=/userservice(?<segment>/?.*), $\{segment}

        - id: authenticationservice
          uri: lb://authenticationservice
          predicates:
            - Path=/authenticationservice/**
          filters:
            - RewritePath=/authenticationservice(?<segment>/?.*), $\{segment}

        - id: appointmentservice
          uri: lb://appointmentservice
          predicates:
            - Path=/appointmentservice/**
          filters:
            - RewritePath=/appointmentservice(?<segment>/?.*), $\{segment}
